name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  # Enable manual trigger for easy debugging
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  version:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: "Use latest"
        id: install-latest
        uses: ./
        with:
          version: latest
          verb: core
          args: version
      - name: "Install latest (check)"
        run: |
          target='${{ steps.install-latest.outputs.output }}'
          if [[ "$target" =~ 'v0\.13\.5' ]]; then
            echo "matches"
            exit 0
          fi
          echo "does not match"
          exit 1


